multi_branch_env:
  hostname: tr.rt.gw
  user: root
  site_url: https://ritvik-bhutani.tr.rt.gw
  main_site: ritvik-bhutani.tr.rt.gw
  deploy_path: /opt/easyengine/sites/ritvik-bhutani.tr.rt.gw/app/htdocs
